# Generated by Django 4.1.7 on 2023-03-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iot",
            options={"verbose_name": "Устройство", "verbose_name_plural": "Устройства"},
        ),
    ]
